### ISSUE TITLE
Alterar para o branch do exercício

### ISSUE THREAD

**Issue by guicompeng** [COLTEC-TP/Android-E03-GUI#3]
Olá, joão, na parte de Configuração do Ambiente deste exercício você pede para alterar o branch do exercício com o comando:  $ git checkout widgets, mas o certo não seria: $ git checkout layouts, já que estamos fazendo o exercício de layouts?
Obrigado!

**Comment by jemaf** [comment]
Olá @guildeassis , bem observado!!

Acabei de corrigir. Muito obrigado!!
